L12 oauth
CaptainPhilipp/qna pull request #13
Opened 2017-06-23 07:46 UTC by CaptainPhilipp

2017-06-24 11:21 UTC, CaptainPhilipp commented on app/controllers/users_controller.rb
> +
вот тут не знаю, правильно ли было ради этого создавать отдельный контроллер.
экшн в `omniauth_callbacks_controller` не получилось сделать - ругается на девайс мэппинг, и известные мне способы (в том числе описанные в самой ошибке) - не помогли.

2017-06-24 11:22 UTC, CaptainPhilipp commented on app/controllers/users_controller.rb
> +  def email
вот тут не знаю, правильно ли было ради этого создавать отдельный контроллер.
экшн в omniauth_callbacks_controller не получилось сделать - ругается на девайс мэппинг, и известные мне способы (в том числе описанные в самой ошибке) - не помогли.

2017-06-24 14:49 UTC, CaptainPhilipp commented on app/controllers/users_controller.rb
> +class UsersController < ApplicationController
вот тут не знаю, правильно ли было ради этого создавать отдельный контроллер.
экшн в omniauth_callbacks_controller не получилось сделать - ругается на девайс мэппинг, и известные мне способы (в том числе описанные в самой ошибке) - не помогли.

2017-06-24 15:54 UTC, CaptainPhilipp commented on app/controllers/users_controller.rb
> +  def email
дофига логики получилось в экшене из-за ветвления. Или норм? Как лучше?

2017-06-24 16:03 UTC, CaptainPhilipp commented on app/controllers/users_controller.rb
> +    end
а еще, то же самое, переписанное на `case` отказалось работать идентично, и выполняло `else`

2017-06-24 19:49 UTC, iBublik requested changes

2017-06-24 19:49 UTC, iBublik commented on app/controllers/users_controller.rb
> +    when proc(&:valid?),  proc(&:confirmed?) then sign_in_and_redirect(user, event: :authorization)
Если честно тяжеловато такие конструкции читать. Как-то не по-рубишному выглядит :)
Видимо поэтому закралась логическая ошибка - в case условия не через && объединяются, а через ||. Т.е. если юзер валиден, всегда будет `sign_in_and_redirect` выполняться

2017-06-24 19:49 UTC, iBublik commented on app/models/user.rb
> +  def self.find_with_uid(args)
Сделай лучше именованные параметры, чтоб было понятно какие аргументы сюда приходят

2017-06-24 19:49 UTC, iBublik commented on app/models/user.rb
> +    create({ password: pass, password_confirmation: pass }.merge args)
Тут можно `reverse_merge` применить, чтоб избавиться от фигурных скобок

2017-06-24 19:49 UTC, iBublik commented on app/services/oauth_user_service.rb
> +  def initialize(request, session)
Сервис получился жестко завязанным на структуры контроллера. Если мы когда-то захотим переиспользовать его, то придется воссоздавать все окружение - request, сессию и т.д.

2017-06-24 19:49 UTC, iBublik commented on app/services/oauth_user_service.rb
> +    @provider = args[:provider]
Зачем всю эту логику извлечения выносить в конструктор? Работа с реквестом - задача контроллера, пускай он сразу передаст все нужные параметры в сервис. Это и тестирование сильно облегчит

2017-06-24 19:49 UTC, iBublik commented on app/services/oauth_user_service.rb
> +    @session  = session
Сессия тут только для того чтоб один раз в нее записать id авторизации. Это очень неявное изменение, которое сложно проследить. Работа с сессией это так же задача контроллера, так что эту логику лучше там держать

2017-06-24 19:49 UTC, iBublik commented on app/services/oauth_user_service.rb
> +  def try_get_user
А почему метод так называется? Он ведь всегда юзера возвращает

2017-06-24 19:49 UTC, iBublik commented on app/controllers/users_controller.rb
> +class UsersController < ApplicationController
По поводу ошибки с ходу не подскажу, можешь на форуме спросить. А в контроллере не вижу ничего плохого

2017-06-24 19:49 UTC, iBublik commented on app/services/oauth_user_service.rb
> +  def save_or_create_user
`find_or_create_user`, наверно

2017-06-24 20:29 UTC, CaptainPhilipp commented on app/models/user.rb
> +  def self.find_with_uid(args)
сначала так и сделал, и в принципе ок, но если передавать цельный хеш, то он его будет воспринимать как один аргумент, который не ожидает

2017-06-24 20:55 UTC, CaptainPhilipp commented on app/models/user.rb
> +    create({ password: pass, password_confirmation: pass }.merge args)
но для этого приходится прописывать `args.to_h`.
странно, но без этого вызывает `ActiveModel::ForbiddenAttributesError`

2017-06-24 20:56 UTC, CaptainPhilipp commented on app/services/oauth_user_service.rb
> +  def initialize(request, session)
вот долго не решался так сделать, но так показалось всё же удобнее

2017-06-24 21:41 UTC, CaptainPhilipp commented on app/controllers/users_controller.rb
> +    end
вот такой вот вариант тоже был. длиннее, но читаемее, хотя не знаю..

а `&&` это хорошо углядели, я бы не скоро заметил (это поведение не тестировал за незначительностью, хотя стоило бы наверное)

2017-06-24 21:44 UTC, CaptainPhilipp commented on app/models/user.rb
> +    create({ password: pass, password_confirmation: pass }.merge args)
специально оставил коммент строки
без `.to_h` отказывается работать `reverse_merge`, кидая ошибку `ForbiddenArgument` от эктив модел (не саппорт)

2017-06-24 21:45 UTC, CaptainPhilipp commented on app/services/oauth_user_service.rb
> +    session[SESSION_KEY] = authentication.id
так более явно, и при том значительно более кратко чем обращаться к сессии в этих целях непосредственно в контроллере

2017-06-24 22:23 UTC, CaptainPhilipp commented on app/models/user.rb
> +  def self.find_with_uid(provider:, uid:, **)
сначала тоже так делал, однако почему-то передача хеша как аргумента в такой ситуации вызывает ошибку `wrong number of arguments (given 1, expected 0)`. Хотя вроде как это должно работать. Без `**` то же самое.

2017-06-24 23:58 UTC, CaptainPhilipp commented on app/models/user.rb
> +  def self.find_with_uid(provider:, uid:, **)
Так тоже делал изначально, но опечалился от того что в аргументы нельзя передать хеш - ругается что ожидается 0 аргументов, а получает 1. без `**` тоже.

2017-06-25 05:55 UTC, iBublik commented on app/controllers/users_controller/oauth_user_policy.rb
> +    email_errors.any? && email_errors.first[:error] == :taken
Можно заменить на `user.errors.added?(:email, :taken)` - короче и нет завязки на то что ошибка должна быть первой

2017-06-25 05:55 UTC, iBublik commented on app/models/user.rb
> +  def self.find_with_uid(provider:, uid:, **)
А зачем сюда хеш передавать? Я понимаю если бы поиск производился по переменному числу аргументов, но ведь он всегда по двум ищет

2017-06-25 05:55 UTC, iBublik commented on app/services/oauth_user_service.rb
> +  def initialize(args)
Тут я бы тоже использовал именованные аргументы. Ведь конструктор ожидает строго 3 значения. С хэшами очень сложно проследить зависимости

2017-06-25 05:55 UTC, iBublik commented on app/services/oauth_user_service.rb
> +    session[SESSION_KEY] = authentication.id
Ну по мне передавать в метод объект чтоб его там поменять - запашок. Так что я бы оставил это в контроллере.

2017-06-25 08:59 UTC, vkurennov approved these changes

2017-06-25 08:59 UTC, vkurennov commented on app/models/user.rb
> +  def self.find_with_uid(provider:, uid:, **)
Я тоже не понял, зачем тут третий аргумент?

2017-06-25 08:59 UTC, vkurennov commented on app/services/oauth_user_service.rb
> +    session[SESSION_KEY] = authentication.id
Не стоит менять сессию вне контроллера. Лучше возвращать хеш из этого метода и записывать его в сессию уже в контроллере. Кроме того, сессию надо очищать после успешного логина. Чтобы не делать этого вручную, можно ключ сессии начать с `"devise."`, тогда devise автоматом очистит такие значения после логина

2017-06-25 08:59 UTC, vkurennov commented on app/services/oauth_user_service.rb
> +  SESSION_KEY = 'devise.oauth_authorization'
А, ну у тебя верно называется ключ. Но в любом случае, это лучше сделать в контроллере.

2017-06-25 13:06 UTC, CaptainPhilipp commented on app/models/user.rb
> +  def self.find_with_uid(provider:, uid:, **)
тупо для удобства. в кристалле так сделано, и вроде бы в руби тоже должно было быть так.

    foo = { a: :aa, b: :bb, c: :cc }
    
    def bar(a:, b:, **)
      [a, b]
    end
    
    bar(foo) # => [:aa, :bb]

2017-06-25 13:13 UTC, CaptainPhilipp commented on app/services/oauth_user_service.rb
> +  def initialize(args)
ну опять же тогда придется передавать не
`new(auth_hash)`, а
`new(provider: auth_hash.provider, uid: auth_hash.uid, info: auth_hash.info)`

2017-06-25 15:26 UTC, CaptainPhilipp commented on app/controllers/omniauth_callbacks_controller.rb
> +      session['devise.oauth_authorization'] = service.get_auth.id
сначала хотел адрес хранить тоже в константе сервиса, но поскольку он теперь никак не связан с сессией, решил дублировать в записи и чтении.

2017-06-25 15:55 UTC, CaptainPhilipp commented on app/controllers/comments_controller/comment_broadcaster.rb
> +class CommentsController
без нэймспейса работает через раз - то находит константу, то падает, не находя.

2017-06-25 15:56 UTC, CaptainPhilipp commented on app/controllers/users_controller/oauth_user_policy.rb
> +      user.errors.added?(:email, :taken)
хорошая фича, спасибо)

2017-06-26 15:02 UTC, merged