L14 api 1
CaptainPhilipp/qna pull request #16
Opened 2017-06-28 17:30 UTC by CaptainPhilipp

2017-06-28 17:31 UTC, CaptainPhilipp commented on app/controllers/api/v1/profiles_controller.rb
> +      User.where.not(id: current_resource_owner.id)
не стоит это меморизировать, верно?

2017-06-28 18:59 UTC, iBublik commented on app/controllers/api/v1/profiles_controller.rb
> +    def users
Почему стандартный index не использовать?

2017-06-28 18:59 UTC, iBublik commented on app/views/api/v1/profiles/me.html.slim
> +h1 Api::V1::Profiles#me
Зачем эти вьюхи? В API мы будем только JSON отдавать

2017-06-28 19:13 UTC, vkurennov requested changes

2017-06-28 19:13 UTC, vkurennov commented on app/controllers/api/v1/profiles_controller.rb
> +    def users
Да, используй стандартный index

2017-06-28 19:44 UTC, CaptainPhilipp commented on app/views/api/v1/profiles/me.html.slim
> +h1 Api::V1::Profiles#me
да чот не подчистил >_<

2017-06-29 05:56 UTC, CaptainPhilipp commented on config/routes.rb
> +        get :index
resource сам не создал :index

2017-06-29 08:31 UTC, vkurennov approved these changes

2017-06-29 19:00 UTC, merged