L15 api 2
CaptainPhilipp/qna pull request #17
Opened 2017-06-30 18:43 UTC by CaptainPhilipp

2017-07-01 19:00 UTC, iBublik requested changes

2017-07-01 19:00 UTC, iBublik commented on app/controllers/api/v1/answers_controller.rb
> +      respond_with @answer = Answer.find(params[:id])
А зачем вообще тут присваивание? Можно ведь просто `respond_with Answer.find(params[:id])`

2017-07-01 19:00 UTC, iBublik commented on app/controllers/api/v1/base_controller.rb
> +    before_action :doorkeeper_authorize!
В API мы так же должны использовать авторизацию (Pundit)

2017-07-01 19:00 UTC, iBublik commented on spec/api/v1/answers_spec.rb
> +RSpec.describe Api::V1::AnswersController, type: :controller do
А почему вдруг controller? Тесты API лучше как request спеки описывать - это более высокоуровневый тест

2017-07-01 19:00 UTC, iBublik commented on spec/api/v1/answers_spec.rb
> +        %w(comments).each do |association|
Тут стоит проверить и атрибуты вложенных объектов

2017-07-01 19:00 UTC, iBublik commented on spec/api/v1/questions_spec.rb
> +            expect(response.body).to_not have_json_path("0/association")
"0/#{association}" - про интерполяцию забыл

2017-07-01 19:00 UTC, iBublik commented on spec/api/v1/answers_spec.rb
> +          it "answer should contain #{field}" do
Рекомендация - не используй should в описании тестов (http://www.betterspecs.org/#should)

2017-07-02 15:21 UTC, CaptainPhilipp commented on spec/api/v1/answers_spec.rb
> +RSpec.describe Api::V1::AnswersController, type: :controller do
действительно. эх, не было этого в скринкасте.
по поверхностному изучению доков так и не понял как заставить его сожрать `format: :json` - либо ругается "не знаю я что такое `format:`", либо игнорирует, возвращая html.

+ тестирование ресурсов с айди. Вроде работает `create :foo, id: 1`, и соответственно `get "path/1"`, но чот не уверен что это хорошо.

2017-07-02 18:25 UTC, iBublik commented on app/controllers/api/v1/profiles_controller.rb
>        return if current_resource_owner.nil?
Полагаю, эта строка теперь избыточна

2017-07-02 18:25 UTC, iBublik commented on spec/api/v1/answers_spec.rb
> +RSpec.describe Api::V1::AnswersController, type: :controller do
Я вижу ты отлично сам справился - молодец :) По второму вопросу - вариант в с передачей `params` более удобен, имхо, а так разницы нет. Можешь смело пользоваться, ничего плохого в этом нет

2017-07-03 07:51 UTC, CaptainPhilipp commented on spec/api/v1/profiles_spec.rb
> +        before { get path, params: { access_token: access_token, format: :json } }
И в этот момент я что-то не понял... Почему тест проходит, и ответ содержит JSON, если в других местах, при точно таком же вызове (при rype: :request), ответ был `HTML`, то есть `format: :json` в лучшем случае игнорировался.

2017-07-03 08:58 UTC, vkurennov approved these changes

2017-07-03 08:58 UTC, vkurennov commented on spec/api/v1/profiles_spec.rb
> +        before { get path, params: { access_token: access_token, format: :json } }
Возможно, дело было не в том, как ты формат запрашивал, а в том, что контроллер не умел в json ответчать (не указал `respond_to :json`) для него.

2017-07-03 11:05 UTC, CaptainPhilipp commented on spec/api/v1/profiles_spec.rb
> +        before { get path, params: { access_token: access_token, format: :json } }
хм. когда спек был контроллер-спеком - работал ок.

2017-07-03 14:03 UTC, merged