L4 controller specs
CaptainPhilipp/qna pull request #2
Opened 2017-04-22 23:17 UTC by CaptainPhilipp

2017-04-22 23:28 UTC, CaptainPhilipp commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answer_question)
что бы не делать лишний запрос в бд

2017-04-23 09:17 UTC, vkurennov requested changes

2017-04-23 09:17 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    params.permit :question_id
если ты хочешь обратиться к params, то не нужно применять permit, вызывай просто нужные данные: `params[:question_id]`. permit важен, когда идет массовое назначение атрибутов, как в create, чтобы не пропустить лишние атрибуты.

2017-04-23 09:17 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answers_params)
Вот здесь лучше сделать запрос к базе и загрузить вопрос, чтобы точно знать, что такой вопрос есть и создать ответ через ассоциации

2017-04-23 09:17 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      .merge answer_question
Плохо. Нельзя добавлять дополнительные параметры к стронг-параметрам "для удобства". Здесь должен быть явно заданный и однозначный белый список параметров, которые мы можем принять из формы. question_id указывается в url, поэтому ничего мержить тут не нужно.

2017-04-23 09:17 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      expect(assigns :answer).to be_a_new(Answer)
у assigns принято всегда ставить скобки

2017-04-23 09:17 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      expect(assigns(:answer).question).to eq(question)
в юинт-тестах, к которым относятся и тетсы контроллеров, принято правило "один тест - один expect", не нарушай его. Да писать чуть больше, зато локализовать проблему в последствии сильно проще.

2017-04-25 06:49 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +    it 'answer\'s question should be right question' do
Можно двойные кавычки использовать, тогда экранировать одинарную не придется

2017-04-25 06:49 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
> +    let(:questions) { create_list :question, 2 + rand(5) }
А зачем тут рандом?

2017-04-25 06:49 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
> +    let(:answers) { create_list :answer, 2 + rand(5), question: question }
Тут тоже непонятно зачем рандом

2017-04-25 06:49 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
> +      let(:attributes) { { title: '', body: '' } }
Лучше использовать атрибуты невалидной фабрики, а не писать вручную - список валидаций всегда может поменяться, и мы просто поменяем определение невалидной фабрики, в тестах ничего менять не придется

2017-04-25 06:49 UTC, iBublik commented on spec/factories/answers.rb
> +    association :question, factory: :question
Это не обязательно, если ты напишешь просто `question`, гем разберется что за фабрику использовать

2017-04-25 06:49 UTC, iBublik commented on spec/factories/answers.rb
> +  factory :invalid_answer, class: Answer do
Если эту фабрику поместить внутрь фабрики `:answer`, то это писать не придется - вложение воспринимается как "наследование" фабрик

2017-04-25 08:08 UTC, vkurennov approved these changes

2017-04-25 08:08 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    it 'answer\'s question should be right question' do
Да, и игнорируй при этом предупреждения рубокопа или RubyMine, одинарные кавычки - не всегда хорошо

2017-04-25 08:08 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    let(:questions) { create_list :question, 2 + rand(5) }
Да, это лишнее и никак не влияет на тесты, по большому счету

2017-04-25 08:15 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +    it 'answer\'s question should be right question' do
Не будет, Rubocop прекрасно понимает что в данном случае двойные кавычки использованы чтоб избежать экранирования

2017-04-25 16:47 UTC, CaptainPhilipp commented on spec/factories/answers.rb
> +  factory :invalid_answer, class: Answer do
ок

Но вот хорошо ли это читается?
мне кажется что как сейчас симпатичнее чем вложенный код

2017-04-25 17:20 UTC, merged