L17 active job
CaptainPhilipp/qna pull request #21
Opened 2017-07-10 17:21 UTC by CaptainPhilipp

2017-07-10 17:24 UTC, CaptainPhilipp commented on config/routes.rb
> +      get    :destroy, on: :collection # for mailer
из письма не получается отправить какой-либо нестандартный метод
(рельса ведь js'ом подправляет метод запроса, а в мейле его, понятное дело, нет)

ну а delete :destroy кастомный т.к. удалять по id подписки пользователям давать нельзя. да и усложняет это. можно юзать просто question и current_user.

2017-07-10 17:26 UTC, CaptainPhilipp commented on spec/features/subscribe_to_questions_spec.rb
> +            expect(page).to_not have_link unsubscribe_link
спек отключен т.к. не работает.

Не работает т.к. после перехода по ссылке, не существует `current_user`, на котором держится удаление подписки. (не передавать же айди юзера в запросе)

Вручную всё работает как надо.

Попробовал по разному, вот даже капибара-сессии подсоединил, но что-то так и не понял как возможно хелпер `current_user` для теста оживить.

2017-07-10 17:29 UTC, CaptainPhilipp commented on spec/features/subscribe_to_questions_spec.rb
> +          mail = ActionMailer::Base.deliveries.last # for deliver_later
после перехода на AJ, в тестах перестали доставляться письма с `deliver_later`.
Как заставить доставлять без костылей - не нашел.
Вставил костылик для чтения непосредственно из очереди.

2017-07-10 17:31 UTC, CaptainPhilipp commented on spec/fixtures/daily/digest
> +Hi, find me in app/views/daily/digest
для чего юзаются эти фикстуры? текст писем для свободного ввода?

2017-07-11 06:03 UTC, iBublik requested changes

2017-07-11 06:03 UTC, iBublik commented on app/controllers/answers_controller.rb
> +  def notify_question_subscribers
Такому коллбэку не место в контроллере. Бизнес-логики в контроллерах быть не должно.
Ну и представь что появится другая точка входа для создания ответа. Придется и туда такой коллбэк пихать. В общем, лучше это в модель вынести

2017-07-11 06:03 UTC, iBublik commented on app/controllers/answers_controller.rb
> +    InstantMailer.notify_about_answer(@answer).deliver_now
Почему deliver_now? Письма надо отложенно отсылать, чтоб пользователь не ждал ответа сервера, пока система письмо отсылает. Ну и представь что при отсылке произошла ошибка - пользователю вернется 500 ошибка

2017-07-11 06:03 UTC, iBublik commented on app/controllers/questions_controller.rb
> +  def subscribe_author
Опять же, контроллер - не место для бизнес-логики

2017-07-11 06:03 UTC, iBublik commented on app/helpers/questions_helper.rb
> +  def subscribed?
Слишком общее название для метода, который во всех вьюхах будет

2017-07-11 06:03 UTC, iBublik commented on app/helpers/questions_helper.rb
> +    Subscription.where(user: current_user, question: @question).limit(1).count.positive?
Слишком сложная логика запроса для вьюхи. Еще и полагаемся, что где-то есть инстанс переменная `@question`
Лучше создай метод `subscribed_to?(question)` в модели юзера. А запрос можно сильно упростить - `current_user.subsriptions.exists?(question: @question)`

2017-07-11 06:03 UTC, iBublik commented on app/mailers/daily_mailer.rb
> +    @new_questions = Question.where('created_at > ?', Date.yesterday)
Выборку "свежих" вопросов лучше в скоуп вынести

2017-07-11 06:03 UTC, iBublik commented on app/mailers/daily_mailer.rb
> +    @new_questions = Question.where('created_at > ?', Date.yesterday)
И вообще ее лучше передавать в мейлер. При 1000 юзеров системы у тебя будет 1000 таких запросов происходить

2017-07-11 06:03 UTC, iBublik commented on app/mailers/daily_mailer.rb
> +                             .where.not(user_id: user.id)
Вот эта строка мешает обощить выборку :) Ну если очень хочется - оставь, правда я не вижу в этом смысла

2017-07-11 06:03 UTC, iBublik commented on app/mailers/instant_mailer.rb
> +    emails = @question.subscriptions.emails
Нехорошо. То есть мой email будет в общем списке с другими подписчиками, они его увидят и смогут мне спам слать :)

2017-07-11 06:03 UTC, iBublik commented on app/models/subscription.rb
> +    all.map { |s| s.user.email }
Жестко. Тут будет n + 1, загрузка кучи данных в память - не надо так. Можно `joins(:user).pluck('users.email')`, но имхо концепция сбора всех emailов в принципе некорректна

2017-07-11 06:03 UTC, iBublik commented on config/routes.rb
> +    resources :subscriptions, only: [:create] do
Можно было сделать подписки единичным ресурсом (`resource :subscription`), т.к. для одного вопроса у одного пользователя может быть только одна подписка. Тогда можно было не создавать вручную роут на удаление

2017-07-11 06:03 UTC, iBublik commented on db/migrate/20170709151140_create_subscriptions.rb
> +      t.references :user, foreign_key: true, null: false
Можно еще уникальный индекс на [question_id, user_id] создать для надежности

2017-07-11 06:03 UTC, iBublik commented on spec/factories/subscriptions.rb
> +    association :user
Можно просто `user`

2017-07-11 06:03 UTC, iBublik commented on spec/factories/subscriptions.rb
> +    association :question
А тут `question`

2017-07-11 06:03 UTC, iBublik commented on spec/features/subscribe_to_questions_spec.rb
> +          mail = ActionMailer::Base.deliveries.last # for deliver_later
Попробуй включить Inline режим для сайдкика конкретно для этого теста
```ruby
Sidekiq::Testing.inline! do
  # Some other tests
end
```

2017-07-11 06:07 UTC, CaptainPhilipp commented on app/controllers/answers_controller.rb
> +    InstantMailer.notify_about_answer(@answer).deliver_now
ой. не доглядел. было later, был уверен что вернул на later >_<

2017-07-11 06:09 UTC, CaptainPhilipp commented on app/mailers/daily_mailer.rb
> +    @new_questions = Question.where('created_at > ?', Date.yesterday)
изначально я и передавал в мейлер. Он ругался что получил чрезвычайно много данных в аргумент, и требовал это исправить.

2017-07-11 06:46 UTC, CaptainPhilipp commented on app/mailers/instant_mailer.rb
> +    emails = @question.subscriptions.emails
а, точно, я и забыл про это

2017-07-11 06:47 UTC, vkurennov commented on config/routes.rb
> +      get    :destroy, on: :collection # for mailer
Можно сделать кастомный метод для отписки, показав там еще форму, где спросить, точно хочешь отписаться? Примерно так у mailchimp сделано. Но это не критично в данном случае, так что ок.

2017-07-11 06:50 UTC, vkurennov commented on spec/features/subscribe_to_questions_spec.rb
> +            expect(page).to_not have_link unsubscribe_link
По идее, отписка из письма не предполагает наличие current_user, т.е. юзер не обязан логиниться. Нужно в ссылке передавать email юзера и id вопроса, по ним искать подписку. Поэтому и делают обычно отдельный url для этого, т.к. логика несколько отличается.
Но вообще-то, нигде не было сказано, что нужно делать отписку из письма :-) Так что сам себе жизнь усложнил

2017-07-11 07:34 UTC, CaptainPhilipp commented on spec/features/subscribe_to_questions_spec.rb
> +            expect(page).to_not have_link unsubscribe_link
тогда любой юзер может отписать от подписки кого угодно - просто подставив их айди. весьма небезопасно. Или тут заморачиваться с токенами и т.п. Проще всего - завязать на `current_user`.

Хотя как пользователя, конечно, бесит, когда хочешь просто отписаться, а от тебя требуют логиниться для этого.

2017-07-11 08:27 UTC, CaptainPhilipp commented on app/models/subscription.rb
> +    all.map { |s| s.user.email }
да, не подумал, жестко.
Твой вариант уже хорош. а вот на счет концепции - один фиг разослать письмо нужно будет каждому подписчику вопроса, и я чот не могу себе представить варианта лучше чем через вот этот `pluck` итерироваться по мылам, и отправлять каждому новый ответ.

2017-07-11 17:46 UTC, CaptainPhilipp commented on db/migrate/20170709151140_create_subscriptions.rb
> +      t.references :user, foreign_key: true, null: false
думал его создать, но не вспомнил где он должен применяться.
хотя такие места есть, пусть и вполне очевидные.

2017-07-11 18:33 UTC, iBublik commented on app/helpers/questions_helper.rb
> +  def subscribed_to?(question)
См. мою рекомендацию https://github.com/CaptainPhilipp/QnA/pull/21#discussion_r126599518
Не вижу смысла такую логику в хелперах держать (я в проектах вообще стараюсь не использовать хелперы)

2017-07-11 18:33 UTC, iBublik commented on app/mailers/daily_mailer.rb
> +    mail to: user.email, subject: 'Daily digest' if @new_questions.any?
Это лучше в вызывающем коде проверить. А то ты для каждого юзера наплодил воркеров с отправкой письма, которые потенциально не сделают ничего полезного

2017-07-11 18:33 UTC, iBublik commented on config/schedule.rb
> +# set :output, "/path/to/my/cron_log.log"
Вычищай ненужные комменты, при необходимости всегда можно к документации обратиться

2017-07-11 18:33 UTC, iBublik commented on db/migrate/20170709151140_create_subscriptions.rb
> +      t.references :user, foreign_key: true, null: false
Это просто контроль целостности данных. Ведь мы полагаемся на то, что у одного юзера может быть лишь одна подписка на вопрос. Конечно у нас вряд ли такая ситация возникнет, но в реальных приложениях я сталкивался с проблемой дубликатов - приходилось данные мержить.

2017-07-11 18:33 UTC, iBublik commented on config/routes.rb
> +    resource :subscriptions, only: %i[create destroy] do
`resource :subscription` - в единственном числе, т.к. это единичный ресурс.

2017-07-11 20:23 UTC, CaptainPhilipp commented on app/helpers/questions_helper.rb
> +  def subscribed_to?(question)
не внимательно прочел >_<

2017-07-11 20:30 UTC, CaptainPhilipp commented on config/schedule.rb
> +# set :output, "/path/to/my/cron_log.log"
вообще, на этом проекте я бы хотел некоторые подобные коменты оставить, на случай желания подсмотреть из кода, а не из доков.

2017-07-11 20:47 UTC, CaptainPhilipp commented on app/mailers/daily_mailer.rb
> +    mail to: user.email, subject: 'Daily digest' if @new_questions.any?
Вот тут не понял. Тестить саму отправку писем в спеках джобы?

И тогда ещё - если я неправильно наплодил джобов, то как стоило бы поступить правильнее?

В принципе, [AnswerNotifyJob](https://github.com/CaptainPhilipp/QnA/pull/21/files#diff-4038a4a303a53dc8737104e570ffa2efR1) я сделал в первую очередь что бы вынести подробности работы с мейлером в отдельную сущность, ибо мне не нравилось что модель знает ещё и эти подробности. Как отдельный джоб оно не очень-то нужно. Вроде как не слишком тяжелая задача - один запрос, раздача задач в цикле.

2017-07-12 05:51 UTC, vkurennov commented on spec/features/subscribe_to_questions_spec.rb
> +            expect(page).to_not have_link unsubscribe_link
Ну так сделай проверку прав, что отписаться может только тот, кто создал подписку. Как-то же мы решали эту задачу для удаления вопроса/ответа

2017-07-12 05:52 UTC, vkurennov commented on spec/fixtures/daily/digest
> +Hi, find me in app/views/daily/digest
Фикстуры - это типа фабрик, только "из коробки".

2017-07-12 05:54 UTC, vkurennov commented on app/mailers/daily_mailer.rb
> +    @new_questions = Question.where('created_at > ?', Date.yesterday)
Да, есть такая проблема, во-первых, AJ не умеет работать с ActtiveRecord::Relation, а во-вторых, при большом объеме массива, тоже может начать на это ругаться.

2017-07-12 05:55 UTC, vkurennov commented on app/helpers/questions_helper.rb
> +  def subscribed_to?(question)
Отсутсвие current_user не проблема, если использовать оператор safe navigation

2017-07-12 06:03 UTC, vkurennov requested changes

2017-07-12 06:03 UTC, vkurennov commented on app/mailers/daily_mailer.rb
> +    mail to: user.email, subject: 'Daily digest' if @new_questions.any?
Тут речь не о тестах, а о том, что вообще нет смысла вызывать DailyMailer.digest в задаче, если массив пустой (причем, он же будет пустым для всех юзеров). И причем тут  AnswerNotifyJob? Это же дайджест, он вызывается  из DailyDigestJob

2017-07-12 06:03 UTC, vkurennov commented on app/policies/subscription_policy.rb
> +    create?
Вот тут маловато проверок, надо проверить, что автором этой подписки является юзер

2017-07-12 06:32 UTC, CaptainPhilipp commented on spec/features/subscribe_to_questions_spec.rb
> +            expect(page).to_not have_link unsubscribe_link
Всё ещё не понятно.
Ну передам я мейл и вопрос, проверю является ли владелец сего мейла подписчиком этого вопроса.
Что помешает мне в эту же ссылку передать email/id других юзеров к этом у вопросу?
Вот и получается что нужен авторизованный пользователь, или уникальная "одноразовая" ссылка.

2017-07-12 06:43 UTC, CaptainPhilipp commented on app/helpers/questions_helper.rb
> +  def subscribed_to?(question)
спасибо, новая фича)

2017-07-12 06:47 UTC, CaptainPhilipp commented on app/mailers/daily_mailer.rb
> +    mail to: user.email, subject: 'Daily digest' if @new_questions.any?
А, господи, до чего же туплю. действительно.
(вот не знаю это я тотально так туплю, или нужно спать больше 5 часов)

2017-07-12 08:41 UTC, vkurennov approved these changes

2017-07-12 08:41 UTC, vkurennov commented on spec/features/subscribe_to_questions_spec.rb
> +            expect(page).to_not have_link unsubscribe_link
Мы тут про 2 разных момента говорим: я про тот, когда юзер авторизован и удаляет подписку из интерфейса приложения, а ты - про отписку из почты. Если говорить про второй случай, то да, тут нужно либо авторизовывать юзера, либо давать уникальную ссылку. Но опять же, этого не было в задании, так что реализация выходит за рамки текущей задачи.

2017-07-12 09:02 UTC, CaptainPhilipp commented on app/models/subscription.rb
> +    all.map { |s| s.user.email }
понял что мыло без юзера - не комильфо, т.к. мы даже поздороваться с юзером по имени в письме не сможем.

2017-07-12 09:52 UTC, CaptainPhilipp commented on spec/features/subscribe_to_questions_spec.rb
> +            expect(page).to_not have_link unsubscribe_link
просто интересно было.

кстати, я таки разобрался почему не было авторизации - ссылка в емейле вела на хост `localhost:3001`, в то время как в тестах хост по умолчанию - `example.com`

2017-07-12 11:21 UTC, merged