L5 acceptance tests
CaptainPhilipp/qna pull request #3
Opened 2017-04-25 17:24 UTC by CaptainPhilipp

2017-04-30 06:52 UTC, webmstk commented on app/controllers/answers_controller.rb
> +      render 'questions/show', id: @question.id
по-моему `id: @question.id` не нужно

2017-04-30 06:52 UTC, webmstk commented on app/views/questions/show.slim
> += render 'answers/form'
где вывод валидационных ошибок?

2017-04-30 06:52 UTC, webmstk commented on app/controllers/answers_controller.rb
> +      @answers = @question.answers
Сюда попадёт в том числе и вновь созданный `@answer`. Даже если он не валиден. Поэтому см. коммент ко вьюхе

2017-04-30 06:52 UTC, webmstk commented on app/views/answers/_answer.slim
> +  = answer.body
Выводить надо только те ответы, которые сохранены в базе (persisted). См. коммент к контроллеру

2017-04-30 06:52 UTC, webmstk commented on spec/models/user_spec.rb
> +  it { should have_many(:answers).dependent(:destroy) }
нужен тест на `.owner?`

2017-04-30 06:52 UTC, webmstk commented on app/views/answers/_form.slim
> +    = f.submit t '.create'
а где перевод? )

2017-04-30 06:55 UTC, webmstk commented on spec/controllers/answers_controller_spec.rb
> +      context 'Anyway' do
не очень понятно

2017-04-30 09:41 UTC, vkurennov requested changes

2017-04-30 09:41 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      render 'questions/show', id: @question.id
Да, не нужно. Достаточно только `render 'questions/show'`

2017-04-30 09:41 UTC, vkurennov commented on app/controllers/answers_controller.rb
>  class AnswersController < ApplicationController
Не реализовано удаление ответа, а оно есть в задании

2017-04-30 09:41 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    redirect_to question_path(@question) unless user_owns_entity? @question
Здесь не обязательно использовать хелпер, можно только метод `User#owner?`, этот фильтр вызывается после аутентификации, поэтому можно быть уверенным, что здесь current_user уже присутствует.

2017-04-30 09:41 UTC, vkurennov commented on app/views/answers/_answer.slim
> +  = answer.body
Да, тут надо добавить проверку на `persisted?`, чтобы невалидных ответов не выводить

2017-04-30 09:41 UTC, vkurennov commented on app/views/layouts/application.html.erb
> +    <%= console if Rails.env == 'development' %>
Так красивее:  `if Rails.env.development?`

2017-04-30 09:41 UTC, vkurennov commented on spec/feature/authorization_spec.rb
> +feature 'User can registrater' do
Каждая фича должна быть в отдельном файле

2017-04-30 09:41 UTC, vkurennov commented on spec/feature/create_answer_spec.rb
> +    scenario 'with valid answer' do
Также нужен сценарий с невалидными атрибутами

2017-04-30 09:41 UTC, vkurennov commented on spec/feature/create_question_spec.rb
> +  scenario 'create Link must works' do
Это не сценарий (описание имею в виду). Сцеенарий - это "пользователь делает то-то". А ссылки вообще проверять не надо, это можно неявно сделать в основных сценариях

2017-04-30 09:41 UTC, vkurennov commented on spec/feature/owner_permissions_spec.rb
> +feature 'Only owner can operate with his entity' do
Здесь речь идет только об удалении, вот и назови фичу "удаление вопроса"

2017-04-30 09:41 UTC, vkurennov commented on spec/feature/owner_permissions_spec.rb
> +  context 'Answer.' do
Удаление ответа - это отдельная фича (которая у тебя не реализована) и должна быть в отдельном файле с тестами

2017-04-30 09:41 UTC, vkurennov commented on spec/feature/user_can_look_answers_spec.rb
> +    5.times { |i| expect(page).to have_content answers[i].body }
А не проще each использовать?

2017-04-30 09:41 UTC, vkurennov commented on spec/feature/user_can_look_questions_spec.rb
> +    5.times { |i| expect(page).to have_content questions[i].title }
И тут тоже each подошел бы лучше

2017-05-06 19:15 UTC, CaptainPhilipp commented on spec/controllers/questions_controller_spec.rb
> +      get :show, params: { id: question }
Тут совсем не понятно.

прежде, было:
```
let(:answers) { create_list :answer, ... }
...
before { get :show, ... }
...
expect(assigns(:answers)).to match_array(answers)

# => PASS
```
то есть сначала отправляется запрос,
`@answers` (содержащий `@question.answers`) на этот момент содержит пустую коллекцию.
Лишь затем, в `...).to match_array(answers)` создаются `answers` у нужного `question`
И уже при проверке `assigns(:answers).to ...` внезапно оказывается,
что в `@answers` чудесным образом они уже есть.
Что за магия такая, откуда они там появились?!

Мне не понятно почему сие **работало**?

Когда я поменял код, и `@answers` в экшене стал содержать не `@question.answers`, а `@question.answers.select(&:persisted)`, всё встало на свои места, и работать перестало, ведь на момент отправки запроса, записей Answer  для `@answers` - не существует, и они появляются только после отправки запроса. - то есть нужно сначала их создать, и лишь затем отправлять запрос.

2017-05-06 19:37 UTC, CaptainPhilipp commented on app/views/questions/show.slim
> += render 'answers/form'
добавил в парциал формы

2017-05-06 19:37 UTC, CaptainPhilipp commented on app/views/answers/_answer.slim
> +  = answer.body
попробовал сделать это в контроллере. как вариант. не уверен что это правильно, но...

2017-05-06 20:33 UTC, CaptainPhilipp commented on spec/models/user_spec.rb
> +  it { should have_many(:answers).dependent(:destroy) }
сделал.

так же добавил еще один метод, но его не стал тестить в силу его примитивности.

2017-05-06 20:33 UTC, CaptainPhilipp commented on app/views/answers/_form.slim
> +    = f.submit t '.create'
+

2017-05-07 10:46 UTC, vkurennov approved these changes

2017-05-07 10:46 UTC, vkurennov commented on app/views/answers/_answer.slim
> +  = answer.body
В контроллере точно не стоит

2017-05-07 13:05 UTC, CaptainPhilipp commented on app/views/answers/_answer.slim
> +  = answer.body
ну там усложнение получилось такое:
вместо `@answers  = @question.answers`
поставил `@answers  = @question.answers.persisted`
и в модели `Answer` объявил этот самый `self.persisted

тоже не стоит?

Тогда - почему в данном случае простую логику лучше оставить во вьюхе, а не в модели с вызовом в контроллере (дважды)?

с одной стороны, да, во вьюхе написал и нет проблем, особенно на этом примере. Но разве не стоит всю логику что возможно перенести из вьюх - перенести куда-то еще?

2017-05-07 17:07 UTC, vkurennov commented on app/views/answers/_answer.slim
> +  = answer.body
Выглядит красиво, но минус в том, что у тебя дважды перебор всех ответов происходит. Логику из вьюх выносить нужно, но не всю. Нужно оставлять логику отображения, т.е. ровно то, за что вьюхи и отвечают. В данном случае это как раз и есть логика отображения

2017-05-07 17:09 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +      get :show, params: { id: question }
Вся штука в том, что в рельсах "ленивые" запросы. Т.е. когда в контрллере мы пишем Answer.all, то запрос не выполняется до тех пор, пока мы с этой коллекцией что-то не будем делать, например итерировать. В match_array внутри как раз вызывается map, и в этот момент как раз и происходит запрос к базе, а тут как раз уже данные созданы.

2017-05-07 17:50 UTC, merged