L6 ajax 1
CaptainPhilipp/qna pull request #5
Opened 2017-05-09 17:56 UTC by CaptainPhilipp

2017-05-09 19:07 UTC, CaptainPhilipp commented on spec/controllers/answers_controller_spec.rb
> +            expect(page).to have_content(I18n.t :errors)
падает: хелпера `page` не существует. от чего - не знаю.
делал bundle update, воюя с установкой нового селениума.

2017-05-09 19:07 UTC, CaptainPhilipp commented on spec/feature/create_answer_spec.rb
>        expect(page).to have_content Answer.human_attribute_name(:body)
Этот экземпл и следующий - по отдельности проходят, но если запускать оба - второй всегда будет падать из за неудачной авторизации. Как исправить - найти пока не смог.

2017-05-09 19:09 UTC, CaptainPhilipp commented on spec/feature/create_answer_spec.rb
>        expect(page).to have_content Answer.human_attribute_name(:body)
Нашел как исправить: [commit](https://github.com/CaptainPhilipp/qna/pull/5/commits/4d5428ed5cbc43cf455255ee9d501b3b5d7f507a)

2017-05-10 09:44 UTC, vkurennov requested changes

2017-05-10 09:44 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      format.html { @answer.save ? redirect_to(@question) : render('questions/show') }
А надо ли теперь поддерживать html?

2017-05-10 09:44 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +            expect(page).to have_content(I18n.t :errors)
А с чего он должен тут существовать, если это тесты **контроллера**, а `page`, как и `have_content` - это хелперы **фичатестов**? Используй хелперы в нужных тестах и все будет хорошо.

И в тестах контроллера мы не проверяем **отображение** чего бы то ни было на старнице. Посмотри, например, как у нас в тесте `QuestionsController` идет проверка на невалидные данные.

2017-05-10 09:44 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +            # TODO: что можно тестить с ajax запросом?
Все то же, что и с обычным запросом. Проблема в том, что ты пытаешься тестировать не то и не там.

2017-05-10 09:44 UTC, vkurennov commented on spec/feature/create_answer_spec.rb
>        expect(page).to have_content Answer.human_attribute_name(:body)
Попробуй по-другому сделать:

```
let!(create(:user))
before { login(user) }
```

`let!` создает данные ДО теста.

2017-05-10 12:12 UTC, CaptainPhilipp commented on app/controllers/answers_controller.rb
> +      format.html { @answer.save ? redirect_to(@question) : render('questions/show') }
а если юзер шифруется, и js вырубил? =)

2017-05-10 18:19 UTC, CaptainPhilipp commented on spec/controllers/answers_controller_spec.rb
> +            expect(page).to have_content(I18n.t :errors)
да, сам себе проблему создал. зачем-то кинул сюда что-то закомментированное, а время спустя, когда увидел закомменченный код, стал считать что он тут всегда был, и его надо оживить.
глупо вышло)

2017-05-10 18:20 UTC, CaptainPhilipp commented on spec/controllers/answers_controller_spec.rb
> +            # TODO: что можно тестить с ajax запросом?
усёк

2017-05-10 18:22 UTC, CaptainPhilipp commented on spec/feature/create_answer_spec.rb
>        expect(page).to have_content Answer.human_attribute_name(:body)
не помогло. много перепробовал настройки `database_cleaner`'a, которых и так не много, но на втором экземпле видно, что после процесса авторизации, пользователь не авторизован.

собсно этот спек хоть и бесполезен сам по себе, но оставлю пока из за этой траблы.

2017-05-11 08:17 UTC, vkurennov approved these changes

2017-05-11 08:17 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      format.html { @answer.save ? redirect_to(@question) : render('questions/show') }
В 2017-м году? Его проблемы :-)

2017-05-11 08:17 UTC, vkurennov commented on spec/feature/create_answer_spec.rb
>        expect(page).to have_content Answer.human_attribute_name(:body)
В общем, я склонировал твой проект и, кажется, нашел в чем проблема. Она не в devise или dbcleaner, а в selenium. Я поставил capybara-webkit в качестве драйвера (это как раз тема следующего урока) и все тесты прошли успешно. Поэтому попробуй поментяь драйвер, как показано в след. уроке и посмотри, пройдет ли тест

2017-05-11 11:38 UTC, CaptainPhilipp commented on spec/feature/create_answer_spec.rb
>        expect(page).to have_content Answer.human_attribute_name(:body)
Спасибо!!!
Буду пробовать

2017-05-11 19:41 UTC, merged