L7 ajax 2
CaptainPhilipp/qna pull request #6
Opened 2017-05-11 22:42 UTC by CaptainPhilipp

2017-05-14 01:20 UTC, CaptainPhilipp commented on spec/feature/best_answer_spec.rb
> +        within "#{sample_answer}.best_answer" do # вместо expect сработает как надо
по сути, within ожидает наличия селектора на странице, и завалит тест, не найдя его, заменив тем `expect(page).to have_selector "#{sample_answer}.best_answer"`
Нормально ли это использовать вместо експекта?

отличие лишь в том что читающий должен знать, что within не прощает отсутствие селектора

2017-05-14 06:58 UTC, vkurennov requested changes

2017-05-14 06:58 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      format.js   { @answer.save; render('create') }
если вид совпадает с названием экшена, то render в контроллере писать не нужно.

2017-05-14 06:58 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      format.js   { @answer.save; render('create') }
Кстати,  `@answer.save` вообще-то в обоих случаях совпадает, поэтому его можно вынести из блока, а в условии для html использовать метод `valid?`

2017-05-14 06:58 UTC, vkurennov commented on app/models/question.rb
> +  belongs_to :best_answer, class_name: 'Answer', optional: true
Плохое решение. Нарушается принцип подчиненности. У тебя ответ принадлежит вопросу, т.е. является дочерним по отношению к вопросу, а вопрос - родительским. При этом, лучший ответ одновременно является дочерним и родительским по отношению к вопросу. 

Лучше было бы сделать флаг у ответов, который бы и обозначал, что ответ лучший. Да, там чуть больше логики надо написать, зато остается простой схема зависимостей, без колец.

2017-05-14 06:58 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  def best_answer
Мы выполняем действие над **ответом**, поэтому экшн должен быть в контроллере ответов.

2017-05-14 06:58 UTC, vkurennov commented on app/views/answers/destroy.js.erb
> +$('#answer_<%= @answer.id %>').replaceWith('')
Используй лучше  функцию `remove`, чтобы просто удалять блок со страницы.

2017-05-14 06:58 UTC, vkurennov commented on spec/feature/best_answer_spec.rb
> +        within "#{sample_answer}.best_answer" do # вместо expect сработает как надо
Да, это неявная проверка, так что ок, но хоть один expect в тесте все равно должен быть

2017-05-14 06:58 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      expect(answer.reload.best?).to be true
`expect(answer.reload).to be_best`

2017-05-14 06:58 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      expect(answer.reload.best?).to be false
`expect(answer.reload).to_not be_best`

2017-05-15 09:19 UTC, vkurennov requested changes

2017-05-15 09:19 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    # respond_to do |format|
Не оставляй закомментированный код, у тебя же контрол версий, всегда можно откатиться или посмотреть прошлые версии. Не зачем хранить хлам в репозитории.

2017-05-15 09:19 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer = Answer.find(params[:id] || params[:answer_id])
Зачем еще `answer_id`? У тебя всегда  в параметре` id` запроса к `AnswersController` должен быть `id` ответа, над которым производится действие. Он же не может быть родительским.

2017-05-15 09:19 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id] || params[:question_id])
Тут тоже `question_id` лишний

2017-05-15 09:19 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  before_action :check_question_ownership!, only: %i(edit update destroy best_answer)
У тебя больше нет метода best_answer

2017-05-15 09:19 UTC, vkurennov commented on app/models/answer.rb
> +    return false unless question.answers.where(best: true).update(best: false)
Вот это надо обернуть в [транзакцию](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html), чтобы изменения были атомарными и либо выполнились все, либо ни одно из них.

2017-05-15 09:19 UTC, vkurennov commented on app/models/answer.rb
> +    return true if best? # без reload, следующая строка не обновляет answers
Данные в базе-то обновляются, это они у объекта не обновляются, поэтому во внешнем вызове да, нужен reload.

2017-05-15 09:19 UTC, vkurennov commented on app/models/question.rb
> +  def best_answer_id
И зачем такой метод, который меняет точку на подчеркивание?

2017-05-15 09:19 UTC, vkurennov commented on app/models/question.rb
> +    Answer.find_by(question_id: id, best: true)
Ты же и так в классе вопроса, используй ассоциации: `answers.where(best: true)`

2017-05-15 09:19 UTC, vkurennov commented on config/routes.rb
> +      patch :best
Кастомный экшн должен указывать для чего он - для коллекции или для одного объекта, от этого зависит, будет передаваться id в url или нет. Посмотри на опцию `on` и на `memeber/collection` в роутах.

2017-05-15 09:19 UTC, vkurennov commented on db/migrate/20170514133418_best_answer_restructurization.rb
> +  def change
А это откатываемая миграция? Что-то не уверен, что change корректно сможет ее откатить...

2017-05-15 09:19 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    let(:send_ajax_request) { patch :best, params: { answer_id: answer.id }, format: :js }
Вот не нужен тут параметр answer_id, если роуты верно прописать, также, как, например он не нужен для update/destroy. Почему-то там нам хватает обычного id...

2017-05-15 09:19 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +          should_not_change(question, :title, :body) { send_request }
откуда should-то взялся? Чем expect с блоком не устроил, как везде до этого?

2017-05-15 09:19 UTC, vkurennov commented on spec/feature/best_answer_spec.rb
> +        expect(question.best_answer).to be nil
в эксептенс-тестах мы не проверяем значения атрибутов, а только то, чтот пользователь видит на странице.

2017-05-15 09:19 UTC, vkurennov commented on spec/feature/best_answer_spec.rb
> +          # после клика селектор должен исчезнуть, но клик не дает эффекта.
Так может, просто js-ответ не верный (с ошибкой) и не выполняется? просто вручную в браузере это работает?

2017-05-15 09:19 UTC, vkurennov commented on spec/feature/best_answer_spec.rb
> +        # падает. клик по ссылке не создаёт ожидаемый эффект - добавление класса
Тогда суть теста вообще не ясна. Если ты ожидаешь добавление класса, то почему проверяешь, что класса нет? (`to_not have_selector`)

2017-05-15 09:19 UTC, vkurennov commented on spec/models/answer_spec.rb
> +  context '#best?' do
Этот метод нет смысла тестировать, потому что не ты его писал, а он автоматически создан рельсами для boolean-атриубута, и твой метод `best!` на наличие этого метода и его поведение никак не влияет

2017-05-15 09:19 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      other_answer.best!
Не нужно использовать тестируемый метод для задания начального состояния. Лучше вручную установить атрибут best в true.

2017-05-15 09:19 UTC, vkurennov commented on spec/models/question_spec.rb
>  RSpec.describe Question, type: :model do
Тут есть метод best_answer

2017-05-15 09:19 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      expect(Answer.where(question: question, best: true).count).to eq 1
У тебя у вопроса есть метод best_answer

2017-05-15 09:19 UTC, vkurennov commented on spec/models/user_spec.rb
> +      expect(other_user_entity.user).to_not eq user # удостовериться в правильности теста
Это ты фабрики тестируешь, а не свой код

2017-05-15 10:11 UTC, CaptainPhilipp commented on spec/feature/best_answer_spec.rb
> +          # после клика селектор должен исчезнуть, но клик не дает эффекта.
суть в том что вручную всё работает

2017-05-15 10:13 UTC, CaptainPhilipp commented on spec/feature/best_answer_spec.rb
> +        # падает. клик по ссылке не создаёт ожидаемый эффект - добавление класса
у блока с answer появляется .best_answer, но убирается линк .best_answer_link
видимо стоит не класс линка проверять, а сам линк. хотя результат одинаковый.

2017-05-15 10:15 UTC, CaptainPhilipp commented on spec/models/answer_spec.rb
> +  context '#best?' do
а. вечно после реструктуризации что-то старое оставляю >_<

2017-05-15 10:16 UTC, CaptainPhilipp commented on spec/models/answer_spec.rb
> +      other_answer.best!
да, чот только сегодня сообразил, перечитывая код. но пушить могу только вечером.

2017-05-15 10:20 UTC, CaptainPhilipp commented on spec/models/answer_spec.rb
> +      expect(Answer.where(question: question, best: true).count).to eq 1
Так тот метод юзает `find_by`, и априори будет давать 0 или 1. а `where` может словить и 2+, если с методом что-то не так. так что юзать best_answer тут более чем бесполезно.

2017-05-15 10:25 UTC, CaptainPhilipp commented on spec/feature/best_answer_spec.rb
> +        expect(question.best_answer).to be nil
ок. просто иногда я стал вставлять експеты не только для проверки валидности тестируемого кода, но и для проверки валидности самого теста.

после такого количества войн с тестами, это показалось не лишним.

2017-05-15 10:27 UTC, CaptainPhilipp commented on spec/controllers/questions_controller_spec.rb
> +          should_not_change(question, :title, :body) { send_request }
да просто хелпер, сокращающий 5-7 строк в общем-то повторяющихся по поведению кода.

не стоит так делать?

2017-05-15 10:35 UTC, CaptainPhilipp commented on app/controllers/answers_controller.rb
> +    @answer = Answer.find(params[:id] || params[:answer_id])
ну.... может я неправильно роут написал?
Потому что в случае с экшеном `#best`, тянется именно answer_id.

Но я перепроверю - роут у меня менялся. Сейчас не уверен что это решение было для последнего вида роута - может для предыдущего, точно не правильного.

2017-05-15 10:36 UTC, CaptainPhilipp commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id] || params[:question_id])
а вот тут точно лишний теперь.

2017-05-15 10:44 UTC, CaptainPhilipp commented on app/models/question.rb
> +  def best_answer_id
когда переносил best_answer из Question в Answer, сначала обеспечил одинаковый интерфейс, что бы к моделям можно было обращаться как прежде. - в новой форме этот метод уже не генерировался, но использовался.

Опять забыл убрать.

2017-05-15 10:48 UTC, CaptainPhilipp commented on db/migrate/20170514133418_best_answer_restructurization.rb
> +  def change
ы. да я чот сначала хотел написать down, оглянул код и подумал что не потребуется.
ок, буду писать откат всегда когда код не может это сделать сам, вне зависимости от почти всех других обстоятельств.

2017-05-15 11:20 UTC, CaptainPhilipp commented on app/models/answer.rb
> +    return true if best? # без reload, следующая строка не обновляет answers
а я подумал что update как раз обновляет объект тоже...

2017-05-15 11:39 UTC, CaptainPhilipp commented on spec/models/user_spec.rb
> +      expect(other_user_entity.user).to_not eq user # удостовериться в правильности теста
это я уже себе перестал доверять, и тестирую что сам написал))

2017-05-15 11:40 UTC, CaptainPhilipp commented on spec/models/question_spec.rb
>  RSpec.describe Question, type: :model do
ок

2017-05-16 05:59 UTC, iBublik requested changes

2017-05-16 05:59 UTC, iBublik commented on app/models/answer.rb
> +    transaction do # простой транзакции без фич вроде должно быть достаточно
Транзакция откатится только если блок бросит исключение. В твоем случае нет кода, который бросит исключение

2017-05-16 05:59 UTC, iBublik commented on app/models/answer.rb
> +    update best: true
А почему бы это в транзакцию не вынести? Иначе не вижу в ней смысла

2017-05-16 05:59 UTC, iBublik commented on app/models/question.rb
> +  def best_answer
Можно заменить на `has_one :best_answer, -> { where(best: true) }`, это даст плюшки вроде мемоизации

2017-05-16 05:59 UTC, iBublik commented on db/migrate/20170513153018_add_best_answer_relation_to_questions.rb
> +class AddBestAnswerRelationToQuestions < ActiveRecord::Migration[5.0]
Зачем это?

2017-05-16 05:59 UTC, iBublik commented on db/migrate/20170514120525_add_best_to_answers.rb
> +    add_column :answers, :best, :bool
Лучше делать `default: false, null: false`, чтоб не было тристейта

2017-05-16 05:59 UTC, iBublik commented on db/migrate/20170514133418_best_answer_restructurization.rb
> +class BestAnswerRestructurization < ActiveRecord::Migration[5.0]
Пока фича не слита в стабильную ветку, не нужно плодить такие миграции. Намного проще откатить и удалить миграцию, добавляющую референс в таблицу вопросов

2017-05-16 05:59 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +        expect { send_request }.to_not change(answer, :body)
Но ведь этот тест никогда не упадет. Без `reload` ты не узнаешь, изменилось ли тело ответа на самом деле

2017-05-16 05:59 UTC, iBublik commented on spec/controllers/answers_controller_spec.rb
> +  describe 'POST #best' do
`PATCH`

2017-05-16 05:59 UTC, iBublik commented on spec/controllers/questions_controller_spec.rb
> +          should_not_change(question, :title, :body) { send_request }
Если очень хочется, то можно написать кастомный матчер для rspec. Хочется видеть консистентность в тестах, а этот кусок выбивается по стилю, и даже не сразу понятно что он внутри делает проверки.

2017-05-16 05:59 UTC, iBublik commented on spec/feature/best_answer_spec.rb
> +          expect(page).to_not have_link best_answer_link
Попробуй посмотреть, вдруг в JS есть ошибки
https://github.com/thoughtbot/capybara-webkit#non-standard-driver-methods

2017-05-16 05:59 UTC, iBublik commented on spec/feature/best_answer_spec.rb
> +          expect(page).to_not have_link best_answer_link
Вполне возможно что в браузере работает, потому что он поддерживает стандарт ES6, но sprockets знаком только с ES5, из-за чего тесты не проходят. Для начала я бы расставил везде `;` в конце строк.

2017-05-16 05:59 UTC, iBublik commented on spec/feature/create_answer_spec.rb
> +      sleep 0.05
Вообще слипы - это не очень хорошо. Они гарантированно замедляют твои тесты. У капибары есть свои матчеры на отрицание (`have_no_content`, 'have_no_link` и т.д.), они внутри периодически чекают что состояние страницы изменилось - это будет эффективнее, т.к. матчер может сработать быстрее чем за 0.05.

2017-05-16 08:26 UTC, CaptainPhilipp commented on app/models/answer.rb
> +    update best: true
чот не догадался.
руководствовался тем что исключение не позволит дойти до `best: true`

2017-05-16 08:26 UTC, CaptainPhilipp commented on app/models/answer.rb
> +    transaction do # простой транзакции без фич вроде должно быть достаточно
ну мало ли какие условия появятся в приложении, что в каких-то условиях не дадут провести одну из `best: false`

другое дело, что следующее действие тоже нужно было включить в транзакцию, а то не правильно как-то.

2017-05-16 08:26 UTC, CaptainPhilipp commented on app/models/question.rb
> +  def best_answer
интересно
сам бы не догадался, спасибо.

2017-05-16 08:26 UTC, CaptainPhilipp commented on db/migrate/20170513153018_add_best_answer_relation_to_questions.rb
> +class AddBestAnswerRelationToQuestions < ActiveRecord::Migration[5.0]
это прежнее решение, которое я переделывал после первого ревью.
Миграции потерявшие смысл тоже стоит удалять? всё таки иногда можно случайно чего-то лишнего почистить, и будет гемор.

2017-05-16 08:26 UTC, CaptainPhilipp commented on db/migrate/20170514120525_add_best_to_answers.rb
> +    add_column :answers, :best, :bool
это было позже добавлено

2017-05-16 08:26 UTC, CaptainPhilipp commented on db/migrate/20170514133418_best_answer_restructurization.rb
> +class BestAnswerRestructurization < ActiveRecord::Migration[5.0]
ух. чутка геморное занятие, но учту.

2017-05-16 08:41 UTC, CaptainPhilipp commented on spec/feature/best_answer_spec.rb
> +          expect(page).to_not have_link best_answer_link
а вот это похоже на правду. проверю

2017-05-16 08:50 UTC, iBublik commented on app/models/answer.rb
> +    transaction do # простой транзакции без фич вроде должно быть достаточно
Тебе надо использовать метод `update!`, т.к. если `update` не выполнится, то он просто вернет `false`, и транзакция завершится.

2017-05-16 16:26 UTC, CaptainPhilipp commented on spec/feature/create_answer_spec.rb
> +      sleep 0.05
have_no_content выглядит как костыль, если он там по сути не нужен.

2017-05-16 16:34 UTC, CaptainPhilipp commented on app/models/answer.rb
> +    transaction do # простой транзакции без фич вроде должно быть достаточно
жаль что update! не существует для коллекции - только для одной записи.

2017-05-16 16:59 UTC, CaptainPhilipp commented on app/models/question.rb
> +  def best_answer
Это, надо полагать, STI?

2017-05-16 21:47 UTC, CaptainPhilipp commented on app/models/question.rb
> +  def best_answer
Не справился с этой штукой - нужен продвинутый дебаг, что бы отловить почему он стал ошибку уникальности кидать. Потом) пока на обычном методе поживу.

2017-05-16 22:05 UTC, CaptainPhilipp commented on app/models/answer.rb
> +      question.answers.where(best: true).each { |a| a.update!(best: false) }
`update!` для коллекции не существует

2017-05-16 22:06 UTC, CaptainPhilipp commented on app/models/question.rb
> +  # has_one :best_answer, -> { find_by best: true }, class_name: 'Answer'
не справился пока. Изучу получше методы дебага, и попробую понять почему ошибки кидает.

2017-05-17 08:36 UTC, vkurennov approved these changes

2017-05-17 08:36 UTC, vkurennov commented on app/models/answer.rb
> +      question.answers.where(best: true).each { |a| a.update!(best: false) }
да, но во-первых, досточно второго `update!`, потому как важно, чтобы прошел именно он, и если он не пройдет, то изменения, сделанные update_all тоже будут откачены. А во-вторых, текущий вариант очень не оптимален, т.к. загружает объекты в память и перебирает по одному.

2017-05-17 09:13 UTC, CaptainPhilipp commented on app/models/answer.rb
> +      question.answers.where(best: true).each { |a| a.update!(best: false) }
Но если второй `update!` не кинет ошибку, а один из update_all хотел кинуть, но не кинул, ибо не `bang!`,
то появится более одного `best_answer`. Тесты конечно за этим следят, но сам механизм становится чуть более хрупким там, где мог бы не становиться.

В добавок, построчный перебор, если всё работает как положено, будет осматривать только одну запись бд.
И только если с системой что-то не так - пробежится по нескольким, и исправит то, что может, (ибо ему по пути), а не усугубит.

2017-05-17 16:46 UTC, merged