L9 ajax events
CaptainPhilipp/qna pull request #9
Opened 2017-05-22 08:46 UTC by CaptainPhilipp

2017-05-24 10:06 UTC, CaptainPhilipp commented on db/schema.rb
> +    t.integer  "value"
null: false, default: 0

2017-05-24 23:04 UTC, CaptainPhilipp commented on app/models/concerns/rateable.rb
> +    (voice = voice_of(user)) && voice.destroy
вот это всё стоит переделать на один метод в интерфейсе, что сможет принимать `0`  вместо `'cancel'`, и не будет удалять запись, что бы индекс реже ворошить.

2017-05-24 23:04 UTC, CaptainPhilipp commented on spec/factories/voices.rb
> +end
по дефолту пока достаточно

2017-05-24 23:04 UTC, CaptainPhilipp commented on spec/feature/vote_answer_spec.rb
> +        page.evaluate_script("window.location.reload()")
более красивый вариант есть?

2017-05-25 04:46 UTC, iBublik requested changes

2017-05-25 04:46 UTC, iBublik commented on app/controllers/concerns/rated.rb
> +    return unless current_user && current_user != rateable_entity.user && params_value
Есть метод `owner`, не дублируй логику

2017-05-25 04:46 UTC, iBublik commented on app/controllers/concerns/public_read.rb
> +module PublicRead
Это уже какой-то overDRY - строк намного больше, чем прописать `skip_before_action` где надо.

2017-05-25 04:46 UTC, iBublik commented on app/controllers/concerns/has_assigned_entity.rb
> +module HasAssignedEntity
Не увлекайся метамагией - читать код становится все сложнее. Лучше в контроллере все явно прописать. Да, чуть больше рутины, зато не надо в десяток модулей лезть, чтоб понять происходящее

2017-05-25 04:46 UTC, iBublik commented on app/models/concerns/has_user.rb
> +module HasUser
Снова overDRY - куча возни ради одной строки.

2017-05-25 04:46 UTC, iBublik commented on app/models/voice.rb
> +  validates :value, numericality: { greater_than_or_equal_to: -1, less_than_or_equal_to: 1 }
`in: -1..1`

2017-05-25 04:46 UTC, iBublik commented on app/models/concerns/rateable.rb
> +    has_many :users, through: :voices
`voted_users`? А то так непонятно что за связь тут

2017-05-25 04:46 UTC, iBublik commented on spec/factories/voices.rb
> +end
У тебя ж констрейнты на уровне БД не дадут такой фабрикой воспользоваться. Смысл создавать невалидную фабрику?

2017-05-25 04:46 UTC, iBublik commented on spec/feature/vote_answer_spec.rb
> +        page.evaluate_script("window.location.reload()")
А зачем это вообще делать? Мы ведь проверяем действие без перезагрузки страницы

2017-05-25 06:11 UTC, CaptainPhilipp commented on spec/feature/vote_answer_spec.rb
> +        page.evaluate_script("window.location.reload()")
в `before` ставить предварительный голос руками вовсе не обязательно, только лишний код. А вот поскольку тут нет запроса, - обновление страницы понадобится.

2017-05-25 06:12 UTC, CaptainPhilipp commented on app/controllers/concerns/rated.rb
> +    return unless current_user && current_user != rateable_entity.user && params_value
точно >_<

2017-05-25 06:12 UTC, CaptainPhilipp commented on app/controllers/concerns/has_assigned_entity.rb
> +module HasAssignedEntity
Ок

2017-05-25 06:14 UTC, CaptainPhilipp commented on app/models/voice.rb
> +  validates :value, numericality: { greater_than_or_equal_to: -1, less_than_or_equal_to: 1 }
о, спасиб. недостаточно доки изучил.

2017-05-25 08:39 UTC, CaptainPhilipp commented on spec/factories/voices.rb
> +end
ну создавалась то она генератором модели, а заполнял я её всё равно кастомными данными.

2017-05-25 08:43 UTC, CaptainPhilipp commented on app/controllers/concerns/public_read.rb
> +module PublicRead
ну... это я взял из мастер-класса по концернам. там был `PublicIndex`, и скип был только на 
на `:index`;
я малость удивился, но раз препод говорит)) тем более, хотелось поиграться с концернами.

хотя у меня этот концерн вообще только в одном месте вставляется - это аргумент еще аргумент против.

2017-05-25 19:58 UTC, CaptainPhilipp commented on spec/controllers/shared_examples/rated_concern_shared.rb
> +        expect(rateable.rating).to eq 1
вот тут я тоже сознательно это делаю, ибо можно не заметить и экземпл запустить неправильно, получив неправильный результат. а так я сразу вижу что что-то пошло не так еще до начала теста.
делаю это обычно там, где такая ошибка более вероятна. Можно конечно говорить что "нужно просто не ошибаться" но это... нувыпоняли.

Или это всё равно плохо?

2017-05-26 08:25 UTC, vkurennov approved these changes

2017-05-26 08:25 UTC, vkurennov commented on app/models/concerns/rateable.rb
> +    (voice = voice_of(user)) && voice.update(value: 0)
Может, проще просто голос удалять? Зачем его хранить?

2017-05-26 08:25 UTC, vkurennov commented on spec/controllers/shared_examples/rated_concern_shared.rb
> +        expect(rateable.rating).to eq 1
Да нет, нормально. Иногда лучше перепроверить.

2017-05-26 08:25 UTC, vkurennov commented on spec/feature/vote_answer_spec.rb
> +        page.evaluate_script("window.location.reload()")
Ну так просто выполни повторный заход на страницу через visit, это лучше чем такой вот костыль.  Тем более, что он делает ровно то же самое, так что логическое дублирование остается. Ну а дублирование кода здесь не так страшно.

2017-05-26 08:38 UTC, CaptainPhilipp commented on app/models/concerns/rateable.rb
> +    (voice = voice_of(user)) && voice.update(value: 0)
ну я поначалу удалял, вчера переделал на 0.
удалять проще, да. но на сколько я понимаю, если туда-сюда удалять-создавать запись, то будет ворошиться индексация. а так - только пополнение таблицы.

2017-05-26 08:47 UTC, merged